---
- name: Set sshd service name
  ansible.builtin.set_fact:
    sshd_service_name: '{{ "ssh" if ansible_distribution == "Ubuntu" and ansible_distribution_version | int <= 14 else ("ssh" if ansible_distribution == "Ubuntu" and ansible_distribution_version | int == 24 else "sshd") }}' # noqa: yaml[line-length]

- name: Allow/disallow SSH password login for root
  ansible.builtin.lineinfile:
    path: '{{ root_ssh_config_path }}'
    regexp: '^\s*#?\s*PermitRootLogin(\s.*)?$'
    line: 'PermitRootLogin {{ "yes" if root_remote_password_login else "without-password" }}'
    validate: 'sshd -t -f %s'
  register: linein_ssh_config

- name: Reload sshd  # noqa: no-handler
  ansible.builtin.service:
    name: '{{ sshd_service_name }}'
    state: reloaded
  when: linein_ssh_config is changed

- name: Update root password
  ansible.builtin.user:
    name: root
    password: '{{ root_password | default(omit) }}'
    password_lock: '{{ true if root_password is not defined else omit }}'

- name: Fix rights on root/.ssh
  ansible.builtin.file:
    state: directory
    path: /root/.ssh
    mode: '0700'
    owner: 'root'
    group: 'root'
