- name: update administrator password
  win_user:
    name: Administrator
    password: '{{ administrator_password }}'
  when: administrator_passord is defined
  no_log: true

- name: allow/disallow SSH password login for root
  lineinfile:
    path: '{{ root_ssh_config_path }}'
    regexp: '^([#]?)(PermitRootLogin) .*$'
    line: '\2 {{ "yes" if root_remote_password_login else "without-password" }}'
    validate: 'sshd -t -f %s'
    backrefs: yes
  register: linein_ssh_configo
  when: root_ssh_config_path != '/etc/ssh/sshd_config'

- name: create directory Administrator/.ssh
  win_file:
    state: directory
    path: "C:\\Users\\Administrator\\.ssh"

