- name: Update administrator password
  ansible.windows.win_user:
    name: Administrator
    password: '{{ administrator_password }}'
  when: administrator_passord is defined
  no_log: true

- name: Allow/disallow SSH password login for root
  ansible.builtin.lineinfile:
    path: '{{ root_ssh_config_path }}'
    regexp: '^([#]?)(PermitRootLogin) .*$'
    line: '\2 {{ "yes" if root_remote_password_login else "without-password" }}'
    validate: 'sshd -t -f %s'
    backrefs: true
  register: linein_ssh_configo
  when: root_ssh_config_path != '/etc/ssh/sshd_config'

- name: Create directory Administrator/.ssh
  ansible.windows.win_file:
    state: directory
    path: "C:\\Users\\Administrator\\.ssh"
